# Generated by Django 4.1.7 on 2023-03-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hakidame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('detail', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='created_at')),
            ],
        ),
    ]
