# Generated by Django 4.1.7 on 2023-03-22 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hakidame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakidame',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hakidame',
            name='todo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hakidame',
            name='detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hakidame',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hakidame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakidame.hakidame')),
            ],
        ),
    ]
