# Generated by Django 4.1.7 on 2023-03-22 12:18

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hakidame', '0002_hakidame_done_hakidame_todo_alter_hakidame_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='hakidame',
        ),
        migrations.AddField(
            model_name='hakidame',
            name='tags',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=6), default=[], max_length=66, size=6),
            preserve_default=False,
        ),
    ]
