# Generated by Django 4.1.7 on 2023-03-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hakidame', '0003_remove_tag_hakidame_hakidame_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hakidame',
            name='tags',
        ),
    ]
