# Generated by Django 4.1.7 on 2023-03-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hakidame', '0004_remove_hakidame_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HakidameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakidame_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakidame.hakidame')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakidame.tag')),
            ],
        ),
    ]
