# Generated by Django 4.1.7 on 2023-03-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakidame', '0005_hakidametag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hakidame',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
