# Generated by Django 4.1.7 on 2023-03-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakidame', '0006_alter_hakidame_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakidame',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hakidametag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hakidametag',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='hakidame',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
